#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> [<subdomain>]
# Display information about subdomains.

# Function to get domain information
get_domain_information () {
    local domain=$1         # The main domain
    local subdomain=$2      # The subdomain
    local record_info       # Variable to store DNS query result

    # Perform a DNS query for the subdomain and store the result
    record_info=$(dig "$subdomain.$domain" +short)
    # Check if a record was found
    if [ -z "$record_info" ]; then
        echo "No record found for $subdomain.$domain"
    else
        # Output the subdomain information
        echo "$subdomain $record_info" | awk '{print "The subdomain " $1 " points to " $2}'
    fi
}

# Check if exactly one argument (domain) is provided
if [ "$#" -eq 1 ]; then
    # Array of default subdomains
    subdomains=("www" "lb-01" "web-01" "web-02")
    # Loop through each subdomain and get its information
    for sub in "${subdomains[@]}"; do
        get_domain_information "$1" "$sub"
    done
# Check if exactly two arguments (domain and subdomain) are provided
elif [ "$#" -eq 2 ]; then
    # Get information for the specific subdomain
    get_domain_information "$1" "$2"
else
    # Print usage instructions if incorrect number of arguments are provided
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi
