#!/usr/bin/env bash
# Script to retrieve and display DNS information about subdomains.

# Function to fetch DNS information for a subdomain of a given domain
fetch_subdomain_info () {
    # Use `dig` to fetch DNS information for the specified subdomain and domain
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    
    # Print formatted output using `awk` to display subdomain, record type, and IP address
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

# Check the number of command-line arguments
if [ "$#" == 1 ]; then
    # If only one argument provided, display information for specific subdomains
    fetch_subdomain_info "$1" "www"    # Display info for www.<domain>
    fetch_subdomain_info "$1" "lb-01"  # Display info for lb-01.<domain>
    fetch_subdomain_info "$1" "web-01" # Display info for web-01.<domain>
    fetch_subdomain_info "$1" "web-02" # Display info for web-02.<domain>
elif [ "$#" == 2 ]; then
    # If two arguments provided, assume the second argument is the subdomain
    fetch_subdomain_info "$1" "$2"     # Display info for specified subdomain
fi
