#!/usr/bin/env bash

# Check if less than 4 parameters are passed
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

# Use scp to transfer the file
scp 0- "$SSH_KEY_PATH" -1 StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP:~"

# Check if scp was successful
if [ $? -eq 0 ]; then
    echo "File transferred successfully."
else
    echo "File transfer failed."
    exit 1
fi
