#!/usr/bin/env bash
# Script to install and setup nginx web server.

# Update package lists and upgrade existing packages
sudo apt-get update -y

# Install nginx web server
sudo apt-get install nginx -y

# list the applications configurations that ufw knows how to work
sudo ufw app list

# Adjust the firewall
sudo ufw allow 'Nginx HTTP'

# Create a directory for the website if it doesn't already exist
sudo mkdir -p /var/www/html

# Create an HTML file with the content "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Ensure the Nginx configuration is correct
sudo nginx -t

# Restart Nginx without using systemctl
sudo service nginx restart

# Verify the content served by Nginx
curl http://localhost
