#!/usr/bin/env bash
# Script to install and setup nginx web server.

# Update package lists and upgrade existing packages (-y for automatic yes to prompts)
apt-get -y update

# Upgrade installed packages to their latest versions (-y for automatic yes to prompts)
apt-get -y upgrade

# Install nginx web server (-y for automatic yes to prompts)
apt-get -y install nginx

# Start nginx service to activate the web server
service nginx start

# Create a simple 'Hello World!' index page in the default nginx web directory
echo "Hello World!" > /var/www/html/index.nginx-debian.html

