#!/usr/bin/env bash
# A bash script that installs nginx on an ubuntu machine.

# Update package lists and upgrade existing packages
sudo apt-get update -y

# Install nginx web server
sudo apt-get install nginx -y

# Create index.html with "Hello World!" content in /var/www/html directory
echo "Hello World!" | sudo dd status=none of=/var/www/html/index.html

# Create 404.html with "Ceci n'est pas une page" content in /var/www/html directory
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Define a new location block for /redirect_me in the Nginx default configuration file
NEW_RULE="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/@innocentsax;\n\t}\n"
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

# Define an error handling for 404 errors in the Nginx default configuration file
NEW_RULE="\\\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"
sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

# Reload nginx configuration to apply changes
sudo service nginx reload
