#!/usr/bin/env bash
# Sets up a new HAProxy as a load balancer

# Ensure the script runs with root privileges
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root. Re-executing with sudo..."
   sudo "$0" "$@"
   exit $?
fi

# Update the package list and install HAProxy
apt-get -y update
apt-get -y install haproxy

# Check if the HAProxy configuration directory exists
if [[ ! -d /etc/haproxy ]]; then
    mkdir -p /etc/haproxy
fi

# Append configuration to HAProxy to handle HTTP requests for the domain techwithjerry.tech
# and distribute them to backend servers using the roundrobin method
echo '
frontend techwithjerry.tech
        bind 0:80              # Listen for incoming connections on port 80
        default_backend web_servers

backend web_servers
        balance roundrobin     # Use the roundrobin method to distribute requests
        server 439093-web-01 54.237.210.164 # First backend server
        server 439093-web-02 34.232.70.144  # Second backend server
' >> /etc/haproxy/haproxy.cfg

# Restart the HAProxy service to apply the new configuration
service haproxy restart
