#!/usr/bin/env bash
# This script pings an IP address passed as an argument to check if the host is reachable.

# Check if there is exactly one argument provided to the script.
if [ $# != 1 ]; then
    # If not, display the correct usage message and exit.
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    # If there is one argument, use the ping command to send 5 packets to the specified IP address.
    ping -c 5 "$1"  # The "-c 5" option limits the number of ping packets to 5.
fi

