#!/usr/bin/env bash
# Script to reset the default server port for Nginx

# Enable the default site by copying its configuration file to the sites-enabled directory
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply the changes
sudo servce nginx restart
