#!/usr/bin/env bash
# Script to configure Nginx to listen on port 80

# Update both IPv4 and IPv6 configurations in one sed command
sudo sed -i -E 's/listen (?:[0-9]{1,3}\.){3}[0-9]{1,3}:8080 default_server;/listen 80 default_server;/' \
               -e 's/listen \[::\]:8080 default_server ipv6only=on;/listen [::]:80 default_server ipv6only=on;/' \
               /etc/nginx/sites-enabled/default

# Send a SIGHUP signal to Nginx to reload the configuration
sudo pkill -SIGHUP nginx
