#!/usr/bin/env bash
# Update the port in Nginx configuration

# Modify the configuration to change the port from 8080 to 80
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply the updated configuration
sudo service nginx restart

# Gracefully stop the Nginx process
sudo service nginx stop

# Start the Nginx service again
sudo service nginx start
