#!/usr/bin/env bash
# Write the script's PID to /var/run/myscript.pid

echo "$$" > /var/run/myscript.pid
# Function to clean up and terminate the script
cleanup_and_exit() {
    # Remove the PID file
    rm -f /var/run/myscript.pid
    exit 0  # Terminate the script
}
# Infinite loop that outputs a message every 2 seconds
while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && cleanup_and_exit' SIGTERM
  trap 'cleanup_and_exit' SIGQUIT
done
