#!/usr/bin/env bash
# This script displays numbers from 1 to 100.

# Loop through numbers from 1 to 100
for number in $(seq 1 100)
do
  if (( number % 3 == 0 && number % 5 == 0 ))
  then
    # Number is a multiple of both 3 and 5
    echo "FizzBuzz"
  elif (( number % 3 == 0 ))
  then
    # Number is a multiple of 3
    echo "Fizz"
  elif (( number % 5 == 0 ))
  then
    # Number is a multiple of 5
    echo "Buzz"
  else
    # Default case, just display the number
    echo "$number"
  fi
done
