#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:

# display hours from 0 to 12
# display minutes from 1 to 59

# Initialize the hour and minute variables
hour=0

# Loop through the hours from 0 to 12
while [ $hour -le 12 ]
do
  # Display the current hour
  echo "Hour: $hour"
  
  # Initialize the minute variable
  minute=1
  
  # Loop through the minutes from 1 to 59
  while [ $minute -le 59 ]
  do
    echo "$minute"  # Print the minute
    minute=$((minute + 1))  # Increment the minute
  done
  
  # Increment the hour
  hour=$((hour + 1))
done
