#!/usr/bin/env bash
# This displays information about the school file.

# Check if the "school" file exists
if [ -e "school" ]
then
  # The file exists
  echo "school file exists"

  # Check if the file is empty
  if [ ! -s "school" ]
  then
    echo "school file is empty"
  else
    echo "school file is not empty"
  fi
  
  # Check if the file is a regular file
  if [ -f "school" ]
  then
    echo "school is a regular file"
  fi

else
  # The file does not exist
  echo "school file does not exist"
fi
