#!/usr/bin/env bash
# Bash script that configures an Ubuntu server

# Overwrite /etc/hosts with the new localhost entry
sudo bash -c 'echo "127.0.0.2    localhost" > /etc/hosts'

# Append the facebook.com entry
sudo bash -c 'echo "8.8.8.8    facebook.com" >> /etc/hosts'

