#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on

# Get all IPv4 addresses from the output of 'ip addr' and extract the IPs
ip addr | grep -Eo "inet ([0-9]+\.){3}[0-9]+" | awk '{print $2}'

