#!/usr/bin/env bash
# Define the server address (replace with your actual server address)
server_address="34.224.6.237"

# Use ssh with single-character flags to connect
ssh -i ~/.ssh/school ubuntu@"$server_address"

