#!/usr/bin/env bash
# Creates RSA key pair

# Name of the private key
key_name="school"

# Number of bits for the key
key_bits=4096

# Passphrase for the key
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $key_bits -f ~/.ssh/$key_name -N $passphrase

